services:
  analyst-shop-api:
    image: analyst-shop-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - analyst_shop_db
  analyst_shop_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: iasa-admin
      POSTGRES_PASSWORD: iasaYZJvLJM
      POSTGRES_DB: analyst_shop_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: